# Generated by Django 4.2.16 on 2024-12-17 23:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Great tournament', max_length=100)),
                ('bio', models.TextField(default='Wonderfull tournament')),
                ('over', models.BooleanField(default=False)),
                ('public', models.BooleanField(default=False)),
                ('number_players', models.PositiveIntegerField(default=4)),
                ('players', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
