# Generated by Django 4.2.16 on 2024-12-01 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('bio', models.TextField(default='Wonderfull tournament')),
                ('end', models.BooleanField(default=False)),
                ('number_players', models.IntegerField(default=4)),
                ('players', models.ManyToManyField(to='tournaments.tournamentplayer')),
            ],
        ),
    ]
