# Generated by Django 4.2.16 on 2024-12-06 18:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('bio', models.TextField(default='Wonderfull tournament')),
                ('end', models.BooleanField(default=False)),
                ('public', models.BooleanField(default=False)),
                ('number_players', models.IntegerField(default=4)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('begin', models.DateTimeField(auto_now_add=True)),
                ('players', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
