# Generated by Django 4.2.16 on 2024-12-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='end',
            new_name='over',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='begin',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(default='Great tournament', max_length=100),
        ),
    ]
