# Generated by Django 4.2.16 on 2024-11-29 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='bio',
            field=models.TextField(default='Wonderfull tournament'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='end',
            field=models.BooleanField(default=False),
        ),
    ]
