# Generated by Django 4.2.16 on 2024-12-02 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_remove_tournament_players'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TournamentPlayer',
        ),
        migrations.AddField(
            model_name='tournament',
            name='begin',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
