# Generated by Django 4.2.16 on 2024-12-02 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_delete_tournamentplayer_tournament_begin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='begin',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
