# Generated by Django 4.2.16 on 2024-12-02 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_friendinvitation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FriendInvitation',
        ),
    ]
