# Generated by Django 4.2.16 on 2024-12-01 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[(0, 'neutral'), (1, 'friend'), (2, 'friend_request'), (3, 'friend_request'), (4, 'blocked'), (5, 'blocked_by')], max_length=20)),
                ('myself', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myself', to='accounts.profile')),
                ('other', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other', to='accounts.profile')),
            ],
        ),
    ]
