# Generated by Django 4.2.16 on 2024-12-01 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_notification'),
        ('relationship', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='myself',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='myself', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='other',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='relation',
            field=models.IntegerField(choices=[(0, 'neutral'), (1, 'friend'), (2, 'friend_request'), (3, 'friend_request'), (4, 'blocked'), (5, 'blocked_by')]),
        ),
    ]
