# Generated by Django 4.2.16 on 2024-12-02 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('relationship', '0002_alter_relation_from_user_alter_relation_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='notifications',
            field=models.ManyToManyField(blank=True, to='notifications.notification'),
        ),
    ]
