# Generated by Django 4.2.16 on 2024-12-01 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship', '0002_alter_relation_myself_alter_relation_other_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='relation',
            field=models.IntegerField(choices=[(0, 'neutral'), (1, 'friend'), (2, 'friend_request'), (3, 'blocked'), (4, 'blocked_by')], default=0),
        ),
    ]
