# Generated by Django 4.2.16 on 2024-12-02 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship', '0003_relation_notifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relation',
            name='notifications',
        ),
    ]
