# Generated by Django 4.2.16 on 2024-12-02 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_delete_friendinvitation'),
        ('relationship', '0004_remove_relation_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendInvitation',
            fields=[
                ('notification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notifications.notification')),
                ('relation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='relationship.relation')),
            ],
            bases=('notifications.notification',),
        ),
    ]
