# Generated by Django 4.2.16 on 2024-12-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship', '0006_alter_friendinvitation_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='relation',
            field=models.IntegerField(choices=[(2, 'neutral'), (0, 'friend'), (1, 'friend_request'), (3, 'blocked')], default=0),
        ),
    ]
