# Generated by Django 4.2.16 on 2024-12-06 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='admin',
            new_name='user',
        ),
    ]
