# Generated by Django 4.2.16 on 2024-12-06 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_game_players_alter_game_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='name',
            field=models.CharField(default='Game!', max_length=30),
        ),
    ]
