# Generated by Django 4.2.16 on 2024-12-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_gamehistory_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamehistory',
            name='duration',
            field=models.DurationField(null=True),
        ),
    ]
