# Generated by Django 4.2.16 on 2024-12-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_alter_gamehistory_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamehistory',
            name='over',
            field=models.BooleanField(default=False),
        ),
    ]
