# Generated by Django 4.2.16 on 2024-12-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_gamehistory_over'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamehistory',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
