# Generated by Django 4.2.16 on 2024-12-12 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_alter_gamehistory_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='owner',
        ),
    ]
